<?php
/**
 * Delivery Date
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Deliverydate
 * @version      10.1.4
 * @license:     5WLwzjinYV1BwwOYUOiHBcz0D7SjutGH8xWy5nN0br
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
// no notice of license for now
?>

<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see Mage_Core_Block_Html_Calendar
 */
?>

<script type="text/javascript">
//<![CDATA[
enUS = <?php echo $enUS?>; // en_US locale reference
Calendar._DN = <?php echo $days['wide']?>; // full day names
Calendar._SDN = <?php echo $days['abbreviated']?>; // short day names
Calendar._FD = <?php echo $firstDay?>; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = <?php echo $months['wide']?>; // full month names
Calendar._SMN = <?php echo $months['abbreviated']?>; // short month names
Calendar._am = <?php echo $am ?>; // am/pm
Calendar._pm = <?php echo $pm ?>;

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "<?php echo $this->__('About the calendar');?>";

Calendar._TT["ABOUT"] =
"<?php echo $this->__('DHTML Date/Time Selector')?>\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"<?php echo $this->__('For latest version visit: %s', 'http://www.dynarch.com/projects/calendar/')?>\n" +
"<?php echo $this->__('Distributed under GNU LGPL. See %s for details.', 'http://gnu.org/licenses/lgpl.html')?>" +
"\n\n" +
"<?php echo $this->__('Date selection:')?>\n" +
"<?php echo $this->__('- Use the %s, %s buttons to select year', '\\xab', '\xbb')?>\n" +
"<?php echo $this->__('- Use the %s buttons to select month', '" + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + "')?>\n" +
"<?php echo $this->__('- Hold mouse button on any of the above buttons for faster selection.')?>";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"<?php echo $this->__('Time selection:')?>\n" +
"<?php echo $this->__('- Click on any of the time parts to increase it')?>\n" +
"<?php echo $this->__('- or Shift-click to decrease it')?>\n" +
"<?php echo $this->__('- or click and drag for faster selection.')?>";

Calendar._TT["PREV_YEAR"] = "<?php echo $this->__('Prev. year (hold for menu)');?>";
Calendar._TT["PREV_MONTH"] = "<?php echo $this->__('Prev. month (hold for menu)');?>";
Calendar._TT["GO_TODAY"] = "<?php echo $this->__('Go Today');?>";
Calendar._TT["NEXT_MONTH"] = "<?php echo $this->__('Next month (hold for menu)');?>";
Calendar._TT["NEXT_YEAR"] = "<?php echo $this->__('Next year (hold for menu)');?>";
Calendar._TT["SEL_DATE"] = "<?php echo $this->__('Select date');?>";
Calendar._TT["DRAG_TO_MOVE"] = "<?php echo $this->__('Drag to move');?>";
Calendar._TT["PART_TODAY"] = ' (' + <?php echo $today ?> + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "<?php echo $this->__('Display %s first', '%s');?>";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = <?php echo $weekendDays?>;

Calendar._TT["CLOSE"] = "<?php echo $this->__('Close');?>";
Calendar._TT["TODAY"] = <?php echo $today ?>;
Calendar._TT["TIME_PART"] = "<?php echo $this->__('(Shift-)Click or drag to change value');?>";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = <?php echo $defaultFormat?>;
Calendar._TT["TT_DATE_FORMAT"] = <?php echo $toolTipFormat?>;

Calendar._TT["WK"] = <?php echo $week ?>;
Calendar._TT["TIME"] = "<?php echo $this->__('Time:');?>";

Calendar.getAbsolutePos = function(element) {

    var res = new Object();
    res.x = 0; res.y = 0;

    // variant 1 (working best, copy-paste from prototype library)
    /*
    do {
        res.x += element.offsetLeft || 0;
        res.y += element.offsetTop  || 0;
        element = element.offsetParent;
        if (element) {
        	//alert(element.tagName);
            if (element.tagName.toUpperCase() == 'BODY') break;
            var p = Calendar.getStyle(element, 'position');
            if (p !== 'static') break;
        }
    } while (element);

    return res;
    */

    // variant 2 (good solution, but lost in IE8)
    if (element !== null) {
        res.x = element.offsetLeft;
        res.y = element.offsetTop;

        var offsetParent = element.offsetParent;
        var parentNode = element.parentNode;

        while (offsetParent !== null) {
            res.x += offsetParent.offsetLeft;
            res.y += offsetParent.offsetTop;

            if (offsetParent != document.body && offsetParent != document.documentElement) {
                res.x -= offsetParent.scrollLeft;
                res.y -= offsetParent.scrollTop;
            }
            //next lines are necessary to support FireFox problem with offsetParent
            if (Calendar.is_gecko) {
                while (offsetParent != parentNode && parentNode !== null) {
                    res.x -= parentNode.scrollLeft;
                    res.y -= parentNode.scrollTop;
                    parentNode = parentNode.parentNode;
                }
            }
            parentNode = offsetParent.parentNode;
            offsetParent = offsetParent.offsetParent;
        }
    }
    return res;
};
//]]>
</script>