<?php
/**
 * Custom Product Preview
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcg
 * @version      11.2.2
 * @license:     AJifvLXz2Jhov40GDpSzkNqfs4dkmEPJtRhHJxJI2y
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">

OptionTemplateCg = '<?php echo Mage::helper("aitcg")->__("You have exceed limit of product for your license."); ?>';

if ($('option_panel_type_file')) {
    $('option_panel_type_file').remove();
}

aitcgImageSelector = new Aitcg.ImageSelectorClosed();
</script>