<style>
    #element_to_pop_up { 
        background-color:#fff;
        border-radius:15px;
        color:#000;
        display:none; 
        padding:20px;
        min-width:400px;
        min-height: 180px;
    }
    .b-close{
        /*cursor:pointer;
        position:absolute;
        right:10px;
        top:5px;*/

    }

    .close-button{
        cursor:pointer;
        position:absolute;
        left:351px;;
        bottom:10px;
    }
    .btn-personalize span{padding:0 0 0 10px !important;}
    .btn-personalize span span{padding:8px 10px 9px 0 !important;}
</style>
<?php $_product = $this->getProduct(); ?>
<div class="lead_time">
    <?php
    $configAttr = $_product->getResource()->getAttribute('flag_leadtime_nextavaiabledate')->getFrontend()->getValue($_product);
    if ($configAttr == "Lead Time") {
        $leadTimeLabel = $_product->getResource()->getAttribute('lead_time')->getFrontend()->getValue($_product);
        if ($leadTimeLabel == "No") {
            $leadTimeLabel = 0;
        }
    }
    if ($configAttr == "Next Available Date"){
        $nextAvaiable=$_product->getResource()->getAttribute('next_available_date')->getFrontend()->getValue($_product);
        
    }
    if ($configAttr == "Lead Time" ):
        echo "Lead Time" . ' : ' . $leadTimeLabel . ' Business Days';
    endif;
    if ($configAttr == "Next Available Date" && !empty($nextAvaiable)):
        echo "Available to ship" . " : " . $nextAvaiable;
    endif;
    ?> </div>
<?php $buttonTitle = $this->__('Add to Shopping bag'); ?>
<?php $buttonTitleName = $this->__('Save and Add to Bag'); ?>
<?php if ($_product->isSaleable()): ?>
        <div class="add-to-cart">
    <?php if (!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Quantity:') ?></label>
            <input type="text" name="qty" id="qty-<?php echo $_product->getId(); ?>" maxlength="12" value="<?php echo (($_product->getMinqty() > 0) ? $_product->getMinqty() : 1); ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
    <?php endif; ?>
    <?php if ($_product->getHasOptions() == 1): ?>

    <?php if ($_product->getTypeId() == "simple") {
 ?>
                    <button type="button" style="display:none;" id="my-buttonadd" title="personalize this item" class="btn btn-primary btn-lg button btn-cart btn-personalize"> <span style="padding:0 0 0 20px !important;"><span style="padding:8px 20px 9px 0 !important;"><?php echo "personalize this item"; ?></span></span></button>
    <?php } if ($_product->getTypeId() == "configurable" && $this->displayConfigurableProductOptions($_product)) {
 ?>
                    <button type="button" style="display:none;" id="my-buttonadd" title="personalize this item" class="btn btn-primary btn-lg button btn-cart btn-personalize"> <span style="padding:0 0 0 10px !important;"><span style="padding:8px 10px 9px 0 !important;"><?php echo "personalize this item"; ?></span></span></button>
<?php } ?>
                <!-- Element to pop up -->
                <div id="element_to_pop_up">
                    <a class="b-close">x<a/>
                        <div id="customOptions"></div>
                        <div id="simpleCustomOption"></div>
                        <button onclick="mainJs();" value="SAVE" type="button" class="button save-btn save-btn_right" ><span><span>Save</span></span></button>
                        <button type="button" id="btnadd-<?php echo $_product->getId() . "_custom"; ?>" class="button save-btn" title="<?php echo $buttonTitleName; ?>"  onclick="mainJs();productAddToCartForm.submit(this)" value="<?php echo $buttonTitleName; ?>" ><span><span><?php echo $buttonTitleName; ?></span></span></button>


<?php /* <button type="button" id="btnadd-save" title="Save" class="button btn-cart" onclick="mainJs();"><span><span><a class="close-button"><?php echo "Save" ?></a></span></span></button> */ ?>
        </div>
<?php endif; ?>
                <button type="button" id="btnadd-<?php echo $_product->getId(); ?>" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
<?php echo $this->getChildHtml('', true, true) ?>
            </div>
<?php endif; ?>
                <script type="text/javascript">

<?php if ($_product->getMinqty() > 0) { ?>
                    ob.minqty.init('<?php echo $_product->getId(); ?>', '<?php echo $_product->getMinqty(); ?>');
<?php } ?>
                </script>
                <script type="text/javascript" src="<?php echo Mage::getSingleton('core/design_package')->getSkinBaseUrl(array('_area' => 'frontend')) ?>/js/jqzoom/jquery.bpopup.js"></script>
                <script type="text/javascript">
                    var typeid=  "<?php echo $_product->getTypeId(); ?>";
                            if(typeid=="configurable")
                            {
                                jQuery("#my-buttonadd").show();
                            }
                            if(typeid=="simple")
                            {
                                jQuery("#my-buttonadd").show();
                            }
                   // jQuery(document).ready(function() {
                        jQuery("input[id$='_text']").each(function() {
                            

                            if(jQuery("#"+this.id).hasClass( "maximum-length-"+parseInt(jQuery("p.note strong#"+this.id).text()) )==true)
                            {

                                jQuery("#"+this.id).attr('maxlength',parseInt(jQuery("p.note strong#"+this.id).text()));
                                // alert(this.id);
                                // jQuery("#"+this.id).val(this.value);
                            }

                        });

                    //});



                    var typeid=  "<?php echo $_product->getTypeId(); ?>";

                    if(typeid=="simple")
                    {

                        if (jQuery('#simpleCustomOption').is(':empty')) {
                            span=jQuery("fieldset#product-options-wrapper dl").clone();
                            jQuery("fieldset#product-options-wrapper dl").remove();
                            //jQuery("div#customOptions").append(jQuery("div#otherproduct-customoptions"));
                            jQuery("div#simpleCustomOption").append(span);

                        }
                    }
                    function mainJs()
                    {
                        //alert("jh");
                        jQuery("input[id^='options_']").each(function() {

                            if(jQuery("#"+this.id).hasClass( "maximum-length-"+parseInt(jQuery("p.note strong").text()) )==true)
                            {

                                jQuery("#"+this.id).attr('maxlength',parseInt(jQuery("p.note strong").text()));

                            }

                            //  var ss=jQuery( jQuery("#"+this.id)).val().replace(" ","[]");
                            //jQuery( jQuery("#"+this.id)).val(ss);

                        });

                        var typeId="<?php echo $_product->getTypeId(); ?>";

        if(typeId=="simple")
        {
            jQuery("#simpleCustomOption dd div.input-box input[id^='options_']").each(function() {

                var inputVal=jQuery("#"+this.id).val().replace("[]"," ");
                // var inputVal=jQuery(this).val().replace(" ","");
                var id=this.id;


                jQuery('<input type=hidden value="'+inputVal+'" id='+id+' name='+jQuery(this).attr("name")+' />').appendTo("#product_addtocart_form");

            });
        }if(typeId=="configurable"){
            jQuery("#customOptions #otherproduct-customoptions dd div.input-box input[id^='options_']").each(function() {
                var inputVal=jQuery(this).val();
                // var inputVal=jQuery(this).val().replace(" ","");
                var id=jQuery(this).attr("id");
                jQuery('<input type=hidden value="'+inputVal+'" id='+id+' name='+jQuery(this).attr("name")+' />').appendTo("#product_addtocart_form");

            });
        }


        jQuery('a.b-close').trigger('click');

    }
    // Semicolon (;) to ensure closing of earlier scripting
    // Encapsulation
    // $ is assigned to jQuery
    ;(function($) {

        // DOM Ready
        jQuery(function() {

            // Binding a click event
            // From jQuery v.1.7.0 use .on() instead of .bind()
            jQuery('#my-buttonadd').bind('click', function(e) {

                // Prevents the default action to be triggered.
                e.preventDefault();

                // Triggering bPopup when click event is fired

                  var typeid=  "<?php echo $_product->getTypeId(); ?>";

                if(typeid=="configurable")
                {

                    if (jQuery('#customOptions').is(':empty')) {
                        span=jQuery("div#SCPcustomOptionsDiv dl div#otherproduct-customoptions").clone();
                       jQuery("div#SCPcustomOptionsDiv dl div#otherproduct-customoptions").remove();
                        jQuery("div#customOptions").append(span);
                        jQuery("div#customOptions div#otherproduct-customoptions").css("display","block");

                    }
                    jQuery("input[id$='_text']").each(function() {


                            if(jQuery("#"+this.id).hasClass( "maximum-length-"+parseInt(jQuery("p.note strong#"+this.id).text()) )==true)
                            {
                                jQuery("p.note").css("color","red");
                                jQuery("#"+this.id).attr('maxlength',parseInt(jQuery("p.note strong#"+this.id).text()));
                                // alert(this.id);
                                // jQuery("#"+this.id).val(this.value);
                            }

                        });

                }
                jQuery('#element_to_pop_up').bPopup();
                //jQuery("#element_to_pop_up").appendTo("dl#custom-options");
                // $span=jQuery("div#otherproduct-customoptions").clone();
                //jQuery("div#SCPcustomOptionsDiv dl div#otherproduct-customoptions").remove();
                //jQuery("div#customOptions").append($span);
                // jQuery("div#customOptions div#otherproduct-customoptions").css("display","block");


            });

        });

    })(jQuery);
</script>