<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" /><br>

        <?php if(!extension_loaded('soap')) { ?>
            <p>
                <strong style="color:red;"> WARNING!! php-soap required</strong>
            </p>
        <?php } ?>
        <?php echo Mage::helper('ebizmarts_sagepaymentspro')->__('<strong style="color:#EA7601;">Sage Payment Solutions PRO v%s </strong> <br>Need help? Got feedback? <a href="mailto:info@ebizmarts.com?Subject=Support SagePaymentsPro">Email us</a>', $this->getVersion())?>
    </h4>
</div>