<?php
$_code = $this->getMethodCode();
$tokenCards = $this->getTokenCards();
$cTokens = ($tokenCards->getSize()>0 && $this->canUseToken());
$sageStyle = ($cTokens ? ' style="display:none;"' : '');
$_directMode = Mage::getStoreConfig('payment/sagepaydirectpro/mode');
//echo "<pre>";print_r($_code);print_r($tokenCards);print_r($cTokens);print_r($sageStyle);print_r($_directMode);
//Mage::log("code=".json_encode($_code),1,"payment.log");
//Mage::log("tokencards=".json_encode($tokenCards),1,"payment.log");
//Mage::log("ctokens=".json_encode($cTokens),1,"payment.log");
//Mage::log("sageStyle=".json_encode($sageStyle),1,"payment.log");
//Mage::log("directMode=".json_encode($_directMode),1,"payment.log");

?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">

    <?php echo $this->getChildHtml(); ?>
    <ul class="form-list paymentsage">

        <?php if($this->canUseToken()): ?>
            <li<?php /*echo $sageStyle;*/ if($tokenCards->getSize()==0 || $cTokens): echo ' style="display:none;"'; endif; ?>>
                <a class="usexist" href="" onclick="toggleNewCard(1); return false;"><?php echo $this->__('Saved Credit Cards'); ?></a>
            </li>
        <?php endif; ?>
        &nbsp;
        <li<?php echo $sageStyle; ?>>
            <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
            </div>
        </li>
        <li<?php echo $sageStyle; ?>>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input autocomplete="off" type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry validate-ccsgpdp-number validate-ccsgpdp-type" value="" />
            </div>
        </li>
        <li<?php echo $sageStyle; ?>>
            <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" onchange="changecsvclass(this);" class="required-entry validate-ccsgpdp-type-select">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input autocomplete="off" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-ccsgpdp-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>


        <?php if($this->canUseToken()): ?>
            <li<?php echo $sageStyle; ?>>
                <label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__('WOULD YOU LIKE US TO SECURELY STORE?'); ?></label>&nbsp;
                <input checked="checked" type="checkbox" name="payment[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
            </li>
        <?php endif; ?>
    </ul>
</div>
