<?php
/**
 * Custom Product Preview
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcg
 * @version      11.2.2
 * @license:     AJifvLXz2Jhov40GDpSzkNqfs4dkmEPJtRhHJxJI2y
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
echo '<?xml version= "1.0"?>'; ?>
<HTML xmlns:v = "urn:schemas-microsoft-com:vml" xmlns="http://www.w3.org/1999/xhtml">
    <HEAD>
        <STYLE></STYLE>
    </HEAD>
    <BODY>
        <?php echo $this->getVmlElements(); ?>
    </BODY>
</HTML>