<?php
/**
 * Custom Product Preview
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcg
 * @version      11.2.2
 * @license:     AJifvLXz2Jhov40GDpSzkNqfs4dkmEPJtRhHJxJI2y
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('aitcg')->__('Easy Tips') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>

<p align=justify >Advertising plays a crucial role to a company's success. The first and key factor is that it makes your audience aware of the products you offer and 
persuades them to choose you.  
<p align=justify >Custom products are unique by their nature, as they fully correspond to the client’s requirements and ideas. How to inform your audience that they 
can order the custom product from your store?  There are numerous ways of online and offline advertising tools either paid or free and it’s up to you 
to choose a proper way and communication channel to deliver your company’s message to your target audience. Below you may find our few easy 
tips to attract more traffic to your store and make your custom product business profitable 

<h4>SEO  </h4>
<p align=justify>There are 2 ways for your web store to appear in search results: content writing or on-page optimization and paid inclusion  
<img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/images.jpg' ?>' style='float:left; width:200px; margin:10px'><p align=justify>1) Find  the  most  relevant  and  popular  keywords  describing  your  web  store  and  products.  Using  these keywords 
throughout your website (as well as in HTML <meta> tags on back-end) will increase your chances to be found by 
your potential customer through search engines and generate traffic.  
<p align=justify>2)  Search  engines  consider  your  store  and  content  relevant.  Paid inclusion  services provided  by  search  engine 
companies  guarantees  that  the  link  to  your  web  store  will  be  displayed  in  search  results  for  specific  keywords. 
Some  engines  indicate paid  advertisements  while  others  show  them  together  with  non-paid. In some  cases  paid 
inclusion  may  also  mean  that  search  bots  will  crawl  you  web  store  more  often  than  non-paid.  By  using  paid 
inclusion you will help your potential client save time on searching your products. They will surely appreciate it. 

<h4>Contextual on-line advertising </h4>
 <img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/index.jpg' ?>' style='float:right; width:150px; margin:10px'><p align=justify>It  is  small  text  with  brief  description  of  your  offers  with  regular  hyperlinks  appearing  on  the  web-sites  that  are 
relevant to  your business.  These ads are highly targeted and therefore are better  accepted by users as they are 
less  annoying and  highly  compliant  with the  particular  search  needs  of  the  user.  For  example,  if  you  provide  golf 
accessories  and  custom  golf  balls a  web  page  (or  search  results)  connected  to  golf  will  automatically draw  your 
contextual ads. In most cases it works as Pay per Click, and it means that you only pay for the user that clicked on 
your ad. 
 
 
<h4><a href='http://www.aitoc.com/en/magentomods_reviews_booster.html'>Testimonials</a></h4>
 <img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/Testimonials.jpg' ?>' style='float:left; width:100px; margin:10px'><p align=justify>Encourage  your  customer  to  leave  a  review  about  your  product. One  of  the  first  things  consumers  look  for  when  considering  a 
purchase is a review. They look to their peers’ experience and trust such reviews far more than advertising.  
 
 
 
<h4>Social media</h4> 
<img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/fb3.jpg' ?>' style='float:right; width:150px; margin:10px'><p align=justify>Create accounts in social media (Facebook, Twitter, Pinterest, Google + ,etc.) where your target audience is most active and 
involve your current or potential customers into discussion. Launch contests or games. Let them share their custom product 
images (Custom Product Preview allows sharing custom product images through Facebook, Google + or e-mail). As a  result, 
the shop gains exposure to new visitors from the customer’s social circle, leading to more sales. 
 
<h4><a href='http://www.aitoc.com/en/magentomods_individual_promotions.html'>Promotions</a></h4>
 
<img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/discounts.jpg' ?>' style='float:left; width:150px; margin:10px'><p align=justify>Use  discounts, coupons, <a href='http://www.aitoc.com/en/magentomods_mail_in_rebates.html'>rebates</a>, establish <a href='http://www.aitoc.com/en/magentomods_loyalty_program.html'>loyalty  program</a>,  etc.  to attract  attention  of new  clients  as  well  as make  your 
current customer more loyal to you. Announce about the promotions. Use the potential of high traffic on-line services as 
Groupon to promote your discounts. 
 
<h4> Newsletters </h4>
<img src='<?php echo Mage::getBaseUrl('media') . 'custom_product_preview/tips/newsletter3.jpg' ?>' style='float:right; width:100px; margin:10px'><p align=justify>Use  newsletters  and  mails  to inform  your  current  customers  about  your  discounts,  new  offers  or  other  useful  and  relevant 
information. 
<p align=justify><i>These are only a few tools to generate more traffic and make your store visible to your target audience. We did not intend to limit your creativity or 
set boundaries in your searching for the right and most effective mechanism to generate more traffic to the store. But you should always keep in mind 
that only proper chosen tools based upon behavioral online characteristics of your target audience may have effect.  
</i>

<p align=center style='font-size:10px'><i>Developed by <a href='http://www.aitoc.com'>aitoc.com</a> </i>