<?php
/**
 * Presnet Category's Product
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<?php
$_productCollection = $this->getCategoryProductCollection();
 $_helper = $this->helper('catalog/output');
?>
<?php // Grid Mode  ?>

<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = '5'; ?>
<?php $i = 0;
foreach ($_productCollection as $_product):
   // echo "<pre>";
  //  print_r($_product->getData());die();?>
        <?php if ($i++ % $_columnCount == 0): ?>
        <ul class="products-grid">
    <?php endif ?>
        <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <h2 class="product-name">
            
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    
                    
                    <?php echo $_product->getName() ?>
                </a>
            
            
            
            </h2>
                <?php echo $this->getPriceHtml($_product, true) ?>
        </li>
    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
        </ul>
    <?php endif ?>
<?php endforeach ?>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>



