<?php
/**
 * Custom Product Preview
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcg
 * @version      11.2.2
 * @license:     AJifvLXz2Jhov40GDpSzkNqfs4dkmEPJtRhHJxJI2y
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
$template_id = $this->getId(); ?>
<?php $_option = $this->getOption(); ?>
<?php $_image = $this->getImage(); ?>
<?php $_rand =  rand(); ?>
<?php $_fileOption = 'options_' . $this->getQuoteOptionId() . '_' . $_rand; ?>
<?php $_fileName = 'options_' . $this->getQuoteOptionId() . '_file'; ?>
<?php /*$_rand = $this->getQuoteOptionCode() . "_" . $this->getQuoteItemId() . "_" . $this->getQuoteOptionId() . '_' . $_rand;*/ ?>
<?php $sharedImgId = $this->getSharedImgId($_rand) ?>
<?php $sharedImgUrl = Mage::helper('aitcg')->getSharedImgUrl($sharedImgId) ?>
<?php //$sharedImgWasCreated = Mage::helper('aitcg')->sharedImgWasCreated($sharedImgId) ?>
<?php $sharedImgWasCreatedUrl = Mage::helper('aitcg')->getSharedImgWasCreatedUrl() ?>

<script type="text/javascript">
//<![CDATA[

AitPopupHtml = '<div id="loading-mask" style="display:none">'+
            '<p class="loader" id="loading_mask_loader">'+
                '<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>'+
            '</p></div>'; 

 
 cimage<?php echo $_rand; ?> = Class.create(<?php echo Mage::helper('aitcg')->getAitcgMainJsClass() ?>,  
    {     
        <?php if($_image !== false): ?>
        productImageThumbnailUrl: '<?php echo $_image["thumbnail_url"]; ?>',
        productImageFullUrl: '<?php echo $_image["full_image"]; ?>',
        productImageSizeX: <?php echo $_image["default_size"][0]; ?>,
        productImageSizeY: <?php echo $_image["default_size"][1]; ?>,
        productImageThubnailSizeX: <?php echo $_image["thumbnail_size"][0]; ?>,
        productImageThubnailSizeY: <?php echo $_image["thumbnail_size"][1]; ?>,
        areaSizeX: <?php echo $this->getAreaSizeX() ?>,
        areaSizeY: <?php echo $this->getAreaSizeY() ?>,
        areaOffsetX: <?php echo $this->getAreaOffsetX() ?>,
        areaOffsetY: <?php echo $this->getAreaOffsetY() ?>,
        jsUrl: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>',  
        <?php endif; ?>
        editorEnabled: false,
        rand: '<?php echo $_rand; ?>',
        text: {
            close: "<?php echo $this->__('Close'); ?>",
            apply: "<?php echo $this->__('Apply'); ?>",
            reset: "<?php echo $this->__('Reset'); ?>",
            required: "<?php echo $this->__('This is a required field.'); ?>",
            texttoadd: "<?php echo $this->__('Text to add...'); ?>",
            addtext: "<?php echo $this->__('Add text'); ?>",
            pickcolor: "<?php echo $this->__('Pick color'); ?>",
            addimage: "<?php echo $this->__('Add image'); ?>",
            svg: "<?php echo $this->__('Save as SVG'); ?>",
            png: "<?php echo $this->__('Convert to PNG'); ?>",
            pdf: "<?php echo $this->__('Save as Pdf'); ?>",
            scale: "<?php echo $this->__('Scale'); ?>"
        },
        product_id: <?php echo $_option->getProductId(); ?>,
        optionId: <?php echo $_rand ?>,
        buttonHelp: "<?php echo $this->__('Save custom image preview to your hard drive (optional)'); ?>",                         
        saveSvgUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl($this->getSaveSvgUrl()); ?>',
        socialWidgetsImgCreatePath : '<?php echo Mage::helper('aitcg')->getImgCreatePath() ?>',
        addMaskUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl(Mage::getUrl('aitcg/ajax/addMask')); ?>',        
        savePdfUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl($this->getSavePdfUrl()); ?>',
        createMaskUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl(Mage::getUrl('aitcg/ajax/createMask')); ?>',        
        getMaskUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl(Mage::getUrl('aitcg/ajax/getMask')); ?>',        
        normalizateSvgToPngUrl: '<?php echo Mage::helper('aitcg')->getSecureUnsecureUrl(Mage::getUrl('aitcg/index/svgtopng')); ?>',
        socialWidgetsReservedImgId : '<?php echo $sharedImgId ?>',
        templateImgPath : '<?php echo $_image['value'] ?>',
        socialWidgetsImgViewUrl : '<?php echo $sharedImgUrl ?>',
        sharedImgWasCreatedUrl : '<?php echo $sharedImgWasCreatedUrl ?>'
    });
opCimage<?php echo $_rand; ?> = new cimage<?php echo $_rand; ?>('<?php echo $_fileOption; ?>');
//]]>
</script>
<div class="input-box" id="<?php echo $_fileOption; ?>_div">
<?php if($_image !== false): ?>
  <div>
      <div class="aitcg_error" style="display: none;">
        <?php echo $this->__('Sorry, but your browser does NOT support HTML5 elements and this feature is not working or may work incorrectly.');?><br />
        <span class="error_default" style="display: none"><?php echo $this->__('Please, try using different browser.');?></span>
        <span class="error_android" style="display: none"><?php echo $this->__('Please, try using different browser (Opera Mini for example) or update your Android to a newer version.');?></span>
      </div>
      <div class="aitcg_image_div"
           style="float:none;"
           id="preview_container<?php echo $_rand ?>"
           onclick="opCimage<?php echo $_rand ?>.startEditor();"></div>
      <input type="hidden" 
             onchange="opConfig.reloadPrice()"
             id="options_<?php echo $_rand ?>"
             name="options[<?php echo $_option->getId() ?>]"
             value='<?php echo $this->getImgData() ?>' />
  
  </div>
<?php endif; ?>

</div>

<?php if(Mage::getStoreConfig('catalog/aitcg/aitcg_use_social_networks_sharing')) : ?>
<!-- aitoc social widgets DO NOT TOUCH THIS LINE !!! -->
<!-- aitoc social widgets inner html DO NOT TOUCH THIS LINE ALSO !!! -->
<br />
<div id="socialWidgetsTip<?php echo $_rand ?>" style="display:none;" onclick="opCimage<?php echo $_rand; ?>.createImage();return false;">
<?php /*<a href="#"><?php //echo $this->__('Click to share your customized image'); ?></a>*/ ?></div>
<div id="imgSizeError<?php echo $_rand ?>" style="display:none;">
<?php echo $this->__('You image exceeds maximum allowed size'); echo ' (' . 
Mage::getStoreConfig('catalog/aitcg/aitcg_social_networks_sharing_max_img_width') . 'x' . 
Mage::getStoreConfig('catalog/aitcg/aitcg_social_networks_sharing_max_img_height') . ')';?></div>
<div class="fb-like" style="visibility:hidden;display:inline;vertical-align:top;" id="fbaitcg<?php echo $_rand ?>" data-layout="button_count" data-href="<?php echo $sharedImgUrl ?>" data-send="true" data-show-faces="false"></div>
<div id="gaitcgWrapper<?php echo $_rand ?>" style="display:inline;"> </div>
    <?php if ($this->canEmailToFriend()): ?>
    <?php $emailToFriendUrl = Mage::helper('aitcg')->getEmailToFriendUrl(Mage::getModel('catalog/product')->load($_option->getProductId()), $sharedImgId) ?>
    <div id="emailToFriend<?php echo $_rand ?>" style="display:none;">
    <p style="display:inline;" class="email-friend"><a href="<?php echo $emailToFriendUrl ?>" target="_blank"><img style="widht:107px;height:20px;" src="<?php echo $this->getSkinUrl('aitoc/aitcg/images') . '/email_to_a_friend.gif' ?>" /></a></p>
    </div>
    <?php endif; ?>
<div id="socialButtonsLoader<?php echo $_rand ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Email to a Friend') ?>" /></div>
<script type="text/javascript">
//<![CDATA[
opCimage<?php echo $_rand ?>.showHideWidgets();
//]]>
</script>
<!-- aitoc social widgets DO NOT TOUCH THIS LINE !!! -->
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
Event.observe(window, 'load', function() {
    opCimage<?php echo $_rand ?>.preview('preview_container<?php echo $_rand ?>');
});
//]]>
</script>