 <?php
 
/**
 * Quickrfq extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FME_Quickrfq
 * @author     Malik Tahir Mehmood<malik.tahir786@gmail.com>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */

 ?>

<div id="success-div" style="display:none">Success div</div>
    
<div id="get-popup" style="display:none;overflow-y: hidden">
	    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	    <div class="page-title">
		<h1><?php echo Mage::helper('quickrfq')->__('ORDER FORM') ?></h1>
	    </div>
	    <form  action="<?php echo $this->getPostActionUrl(); ?>" method="post" enctype="multipart/form-data" id="quickrfq_form">
                <div class="fieldset">
		    <h2 class="legend"><?php //echo Mage::helper('quickrfq')->__('Order form') ?></h2>
            <h3 class="legend"><?php echo Mage::getStoreConfig('quickrfq/option/order_form_text');?></h3>
            <h2 class="legend"><?php //echo Mage::helper('quickrfq')->__('Order form') ?></h2>
		    <ul class="form-list">
			<li>
			    <label for="company" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('First Name:') ?></label>
			    <div class="input-box">
				<input style="font-size:14px;" name="company" value=""  type="text" size="29" class="input-text required-entry"/>
			    </div>
			</li>
			<li class="fields">
			    <div class="field">
				<label for="name" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('Last Name:') ?></label>
				<div class="input-box">
				    <input style="font-size:14px;" name="contact_name" id="name" title="<?php echo Mage::helper('quickrfq')->__('Contact Name') ?>" value="<?php echo $this->htmlEscape($this->helper('quickrfq')->getUserName()) ?>"  size="29"  type="text" class="input-text required-entry" /></td>
				</div>
			    </div>
			</li>
			<li class="fields">
			    <div class="field">
				<label for="email" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('Email:') ?></label>
				<div class="input-box">
				    <input style="font-size:14px;" name="email" id="email" title="<?php echo Mage::helper('quickrfq')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('quickrfq')->getUserEmail()) ?>"  size="29" type="text" class="input-text required-entry validate-email"/>
				</div>
			    </div>
			</li>
		       <li>
			    <label for="telephone" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('Phone:') ?></label>
			    <div class="input-box">
				<input style="font-size:14px;" name="phone" id="telephone"  class="input-text validate-phoneStrict" type="text" size="29" />
				<p>For example (123) 456-7890 or 123-456-7890</p>
			    </div>
			</li>
			
			<li>
			    <label for="prefered-methods"><?php echo Mage::helper('quickrfq')->__('Prefered Method of  Contact:') ?></label>
			    <div class="input-box">
			       <input name="prefered_methods[]" value="email" checked="checked" type="checkbox"><?php echo Mage::helper('quickrfq')->__('Email') ?>
			       <input name="prefered_methods[]" value="phone" type="checkbox"><?php echo Mage::helper('quickrfq')->__('Phone') ?>
			       
			    </div>
			</li>
			<li>
			    <label for="date"><?php echo Mage::helper('quickrfq')->__('When do you need your cookie or cupcakes by ?:') ?></label>
			    <div class="input-box">
				<input style="font-size:14px;" value="<?php echo $this->getEstimateDate() ?>" id="calendar-inputField" name="date">
				    <img id="calendar-trigger" src="<?php echo $this->getSkinUrl() ?>images/quickrfq/cal.gif" width="20px" height="20px" style="" />
			    </div>
			</li>
			
			<li>
			    <label for="title" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('How many cookies or cupcakes do you need?:') ?></label>
			    <div class="input-box">
				<input style="font-size:14px;" name="number_cookies" id="title" type="text" size="29" class="input-text validate-greater-than-zero required-entry"/>
			    </div>
			</li>
			<li>
			    <label for="occasion" ><?php echo Mage::helper('quickrfq')->__('What is the occasion or theme?:') ?></label>
			    <div class="input-box">
				<input style="font-size:14px;" name="occasion" id="occasion" type="text" size="29" class="input-text"/>
			    </div>
			</li>
			
			<li>
			    <label for="status"><?php echo Mage::helper('quickrfq')->__('What are these cookies or cupcakes being used for?:') ?></label>
			    <div class="input-box">
			       <input name="budget[]" value="Serve at an event" checked="checked"  type="checkbox"><?php echo Mage::helper('quickrfq')->__('Serve at an event') ?>
			       <input name="budget[]"  value="Party Favors" type="checkbox"><?php echo Mage::helper('quickrfq')->__('Party Favors') ?>
			       <br>
			       <input name="budget[]"  value="Gift" type="checkbox"><?php echo Mage::helper('quickrfq')->__('Gift') ?>
			       <input name="budget[]"  value="Promotinal Material" type="checkbox"><?php echo Mage::helper('quickrfq')->__('Promotinal Material') ?>
			    </div>
			</li>
			<li class="wide">
			    <label for="quickrfq" class="required"><em>*</em><?php echo Mage::helper('quickrfq')->__('Please summarize what you would like to create:') ?></label>
			    <div class="input-box">
				<textarea name="overview" id="overview" title="<?php echo Mage::helper('quickrfq')->__('Brief Overview') ?>" class="input-text required-entry" style="font-size:14px;" name="overview" cols="55" rows="30" id="project_overview"></textarea>
			    </div>
			</li>
			    
			 
			<li>
			    <label for="file"><?php echo Mage::helper('quickrfq')->__('Upload Document:') ?></label>
			    <div class="input-box">
				<?php echo $this->getUploadFile() ?>
				<br>
				  <p> You can upload files with these file extensions only (<?php echo $this->getAllowedExtensions() ?> )</p>
			    </div>
			 </li>
			   
            
             
		    </ul>
		</div>
		<div class="buttons-set">
		    <p class="required"><?php echo Mage::helper('quickrfq')->__('* Required Fields') ?></p>
		    <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
		    <button type="submit" title="<?php echo Mage::helper('quickrfq')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('quickrfq')->__('Send Request') ?></span></span></button>
		</div>
		
            </form>
</div>
		 <script>//<![CDATA[
		Calendar.setup({ trigger: "calendar-trigger", inputField: "calendar-inputField" });
		//]]></script>
		
		<script type="text/javascript">
		//<![CDATA[
		    var contactForm = new VarienForm('quickrfq_form', true);
		//]]>
		</script>
               

